### ISSUE TITLE
Add Figure Caption

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#10]
Add a caption to a figure.

**Comment by jwz2kn** [comment]
The medium-editor-insert-plugin for insert pictures and videos does allow captioning on pictures. https://github.com/orthes/medium-editor-insert-plugin

Not sure if we're sticking with this in the long run, but it's the plugin that medium-editor has on their site, and our ongoing search for alternatives hasn't produced a better plugin yet.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#10
