### ISSUE TITLE
Integrate the React version of DraftFinal with Flask

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#100]
Flask is a Python framework for web applications. It allows for some cool interactions between different webpages and some data sent back and forth. Porting DF over to a framework like Flask allows us to set up a more robust backend, which in turn might allow more interesting features like user profiles, saving, etc.

See issues #101, #102, #103, #104.

**Comment by jwz2kn** [comment]
The issues described now work, but there’s a good amount of code cleanup and organization we’ll need to do.

Also, everything may be ported to Flask, but it’s not taking full advantage of React or Flask’s powerful capabilities yet. One of the cool things that Flask allows you to do easily is navigate between webpages easily and pass info back and forth between html pages, and we’re working on a small demo of that.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#100
