### ISSUE TITLE
Comments default avatar broken

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#105]
Comments default avatar broken after porting to Flask.

**Comment by jwz2kn** [comment]
Doesn't work on all computers/browsers. At the moment, adblocking programs are kinda iffy with this... The no-cache thing may/may not work, but you need to disable adblock on DF, refresh, and reenable adblock, and the default avatar works again...

**Comment by jwz2kn** [comment]
Caching issue fixed, credit to Calvin implementing http://stackoverflow.com/questions/13768007/browser-caching-issues-in-flask

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#105
