### ISSUE TITLE
Build demo feature for Flask/React version of DF

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#106]
We'll build a demo of a login page to show off the cool backend managing that Flask allows.

**Comment by jwz2kn** [comment]
https://github.com/BluestoneLogic/medium-editor/commit/e405590d9f806ede354aa71388a689dc4f8f998d

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#106
