### ISSUE TITLE
Automatic URL unfurling

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#13]

**Comment by cml5gm** [comment]
https://github.com/orthes/medium-editor-insert-plugin might be useful

**Comment by eban5** [comment]
Please add a description. I think we might want to avoid automatic unfurling and rather let that be something the user toggles. welcome thoughts.

**Comment by cml5gm** [comment]
Closing this issue. While unfurling would be a nice feature, the average DraftFinal user would have no use for link unfurling (would Bob ever embed a Tweet in a document?). We believe the user's workflow would be better supported by a more robust image upload plugin, so we plan to shift our focus to that. See issues #81 and #82

**Comment by dahearn** [comment]
I'm okay with deprioritizing this, but I'm having trouble agreeing with the premise that a user would not want linked information unfurled in some cases.  The twitter example is not the primary use in my mind, more a URL to a website unfurling like Slack does.

Don't get fixated on users creating a "document", users will be curating and creating "content" on a "canvas."  This content could be in the form of loose quick notes, where you could definitely see a real benefit to unfurling... imagine the alternative... an ugly list of url addressed pasted as text.

I agree that unfurling is not ideal for a document intended to be printed, but DraftFinal is intended to live in a post-paper world.

**Comment by jwz2kn** [comment]
@cpark15 and I will try to get the following sites to unfurl:
www.medium.com/bluestone-logic
www.techcrunch.com
www.stackoverflow.com
www.github.com
www.youtube.com

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#13
