### ISSUE TITLE
Spreadsheets

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#17]

**Comment by cml5gm** [comment]
https://github.com/asselinpaul/medium-editor-handsontable this might be useful.

**Comment by eban5** [comment]
@cml5gm Please add some text to the description. Are we displaying a spreadsheet like an Excel file stored on Box? How would that be different from Viewing a BLOB File in #22 ?

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#17
