### ISSUE TITLE
Rastered Image

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#18]
Add raster image to canvas.

**Comment by eban5** [comment]
via Drag and Drop? via "Attach Image" toolbar extension?

**Comment by jwz2kn** [comment]
@eban5 I think drag and drop already works in a lot of cases (doesn't work for .gifv formats). Interestingly enough, copy-paste images are often broken.

**Comment by eban5** [comment]
My comment was that this description needs to be refined. Could be split into two where one is "via drag and drop" and the other "via image attachment button" or similar.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#18
