### ISSUE TITLE
Query a database

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#24]
Ability to query a database and view results based within editor

**Comment by eban5** [comment]
This user story seems to have come out of the "Reference Database" index card; however, this needs some explanation and more detail about what was meant. I'm not sure that allowing random database querying from an editor is something we want to allow or is even useful.

**Comment by eban5** [comment]
We need to discuss this at the Sprint 2 demo.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#24
