### ISSUE TITLE
Greyscale an image

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#26]

**Comment by eban5** [comment]
Is the purpose to make printing without color easier? This feels like a "prep for export" user story but I am OK with leaving it if we feel like it is important.

**Comment by jwz2kn** [comment]
@eban5 This is definitely more of a prep for export. Let's take this one out.

**Comment by jwz2kn** [comment]
We won't work on this for the prototype-- It's not central to content creation.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#26
