### ISSUE TITLE
Second toolbar that will house the structure changes 

### ISSUE THREAD

**Issue by cpark15** [BluestoneLogic/medium-editor#27]
Add another toolbar that links paragraphs. Similar functionality to Slack.

**Comment by eban5** [comment]
## Example

### Second toolbar appears to the left of the paragraph when selecting some text
![screen shot 2016-07-18 at 1 15 37 pm](https://cloud.githubusercontent.com/assets/11206366/16923743/c16cb9f4-4ce9-11e6-9067-6add3dda8b88.png)

### Second toolbar options are primarily for structuring content or creating headers.
![screen shot 2016-07-18 at 1 15 20 pm](https://cloud.githubusercontent.com/assets/11206366/16923769/eff4bdee-4ce9-11e6-972f-c43eaee560fa.png)

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#27
