### ISSUE TITLE
Cannot undo code formatting

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#30]
Once text is formatted using "code," it cannot be undone unless the user types Meta+Z.

**Comment by eban5** [comment]
@cml5gm Which "code" formatting did you mean? I'm only seeing the `</>` toolbar option, which shows you the grey box with dark grey monospace font text (I've been calling that "preformatted text"). If it is the preformatted box, then I was able to enable and disable the formatting with the button toggle. Maybe some code wasn't firing off when you tried earlier?

**Comment by cml5gm** [comment]
@eban5 I was referring to the "pre-formatted text." It looks like you've fixed it, so I'll close it now.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#30
