### ISSUE TITLE
InfoBox/WarningBox/ErrorBox on top of InfoBox/WarningBox/ErrorBox

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#35]
Refer to #1

The user can accidentally place a box (info/warning/error) on top of the toolbar on infobox/warningbox/errorbox.

To replicate this error: highlight some text and open the toolbar. then right click on the button for infobox/warningbox/errorbox (this will highlight the text on these buttons). now click infobox/warningbox/errorbox. 

![screen shot 2016-07-12 at 9 24 51 am](https://cloud.githubusercontent.com/assets/9540866/16768611/022b87bc-4813-11e6-966a-4e83bca2a16f.png)

**Comment by eban5** [comment]
Closing this since it was fixed after highlighting any toolbar items was disabled.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#35
