### ISSUE TITLE
Callout boxes nest each other

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#36]
Refer to #1
![screen shot 2016-07-12 at 10 46 28 am](https://cloud.githubusercontent.com/assets/11744033/16771294/ef4e5e48-481d-11e6-8213-f1b622068f98.png)

**Comment by eban5** [comment]
A user can get out of them by backspacing but I'm inclined to mark this as **won't fix** for now.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#36
