### ISSUE TITLE
Prototype doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#40]
The toolbar buttons do not appear
![ie_medium-editor](https://cloud.githubusercontent.com/assets/9540866/16804947/154df798-48dc-11e6-866b-1a211fc8be32.JPG)

**Comment by cpark15** [comment]
Fixed issue, commit is listed below
https://github.com/BluestoneLogic/medium-editor/commit/7cba7cfa6c694f53e300577fc3b4c151f1bbf7bf

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#40
