### ISSUE TITLE
Disallow header formatting

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#43]
As the user, I don't want to format my headers into bold, italicized, or strikethrough text.

**Comment by eban5** [comment]
@cml5gm Wasn't this resolved before the Sprint 1 demo?

**Comment by jwz2kn** [comment]
@eban5 No, this was resolved only for title, not all the headers.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#43
