### ISSUE TITLE
Annotations are deleted once the switch is turned off 

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#49]
The script currently destroys the instance of the annotator when turned off, which deletes all previous annotations. This was because we could not locate a function to pause the annotator. To fix this, determine how to stop the annotator without deleting comments. Once this function is found, find lines 155-159 in bl-test.html and change app.destroy() to the correct function.

`else {
                app.destroy();
                switchClick++;
                console.log("Annotator is off");
            }`

**Comment by cml5gm** [comment]
Potential solution: change CSS visibility to hidden when switch is off.

**Comment by eban5** [comment]
The only that this problem persists is if we go back to using AnnotateJS as our annotation engine. Leaving this as an active bug for now since it is major.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#49
