### ISSUE TITLE
Firefox and IE does not reset slider when page is refreshed

### ISSUE THREAD

**Issue by cpark15** [BluestoneLogic/medium-editor#51]

**Comment by eban5** [comment]
It seems like the slider state is actually inverted when refreshed on Firefox.

1. Add some dummy content, turn on annotations, and annotate some text.
1. refresh the page, note the annotation slider is blue (on) but the annotations button doesn't appear on text highlight
1. when you click the annotation slider to greyed out (off) and select text, you will be able to annotate. 

It's like the state has been flipped. Check the variable where you set the state of the annotations slider.

**Comment by eban5** [comment]
Not likely that we will keep this slider, but marking this as **won't fix** for now.

**Comment by cml5gm** [comment]
We are not keeping the annotation slider. Therefore, I am closing this issue.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#51
