### ISSUE TITLE
Text becomes unformatted when you backspace into header

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#52]
To replicate: start at the beginning of text, directly following a header. Press backspace so that the text is inline with the header. Then press enter to put the text below the header (as it was initially). 

The text becomes smaller, and unformatted.
![screen shot 2016-07-14 at 3 41 48 pm](https://cloud.githubusercontent.com/assets/9540866/16853269/acecf51a-49d9-11e6-93d0-b70a8ae841f4.png)

**Comment by eban5** [comment]
Strangely, if you select that text that has become "unformatted" and press "remove formatting" in the toolbar, you restore the plain paragraph format. Marking this as **won't fix**.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#52
