### ISSUE TITLE
Limit number of characters in title

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#59]
titles can have an infinite length, causing issues.

**Comment by cml5gm** [comment]
When resolving this issue, we encountered a new bug. When in the CSS format, the "overflow: auto" field causes the two lines to be different lengths. For the demo, we're reverting the commit because it looks cleaner.

**Comment by eban5** [comment]
@cml5gm what is the issue being caused by a long title? What is the max character length for this prototype?

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#59
