### ISSUE TITLE
Make annotation slider prettier 

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#61]
It looks ugly to have a switch with a label above it. Make it prettier.

**Comment by jwz2kn** [comment]
This was much more relevant when we used the simple version of annotation.js. We then tried hypothesis, which we decided to abandon because it's difficult to host an on-prem version. Leaving this open for now, but depending on what we'll use for annotation/commenting, might close this.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#61
