### ISSUE TITLE
Autoformat list includes a space in the first bullet/number

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#63]
To replicate: press * + [space] 
then begin typing

**Comment by cml5gm** [comment]
Update: tried to fix using .unbind(). We use preventDefault() to disable SPACE and make SPACE create a list. However we cannot figure out a way to undo preventDefault() once the list is created

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#63
