### ISSUE TITLE
Cannot add columns once a table is made

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#70]
Once a table is initialized, the user cannot add extra columns. (rows **can** be added)

**Comment by jwz2kn** [comment]
![table column add](https://cloud.githubusercontent.com/assets/11744033/16950992/ff28ec48-4d90-11e6-8437-b3139fc24873.png)

Extra columns and rows can be added, although reproducing that menu can be difficult.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#70
