### ISSUE TITLE
Restore README and check nothing else was overwritten

### ISSUE THREAD

**Issue by eban5** [BluestoneLogic/medium-editor#73]
### our readme got overwritten by one from JQuery Insert Plugin. Please revert and check our other files didn't get overwritten.

**Comment by cml5gm** [comment]
Changed README to blank "coming soon" page. While some other files were overwritten by JQuery Insert Plugin (bower.json being one), no functionality seems to be affected. Closing issue.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#73
