### ISSUE TITLE
TOC/Canvas navigation that follows users headers

### ISSUE THREAD

**Issue by eban5** [BluestoneLogic/medium-editor#74]
### Some sort of navigation helper would be useful if the user is writing a lot of content. Our canvas is considered an endless scrolling one (like Medium or Slack Post). We want to have some sort of TOC that follows the user.

**Comment by dahearn** [comment]
This is definitely a good thing... possibly another "view" in the sidebar

**Comment by eban5** [comment]
Adding this as a view in the sidebar.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#74
