### ISSUE TITLE
Formatted content will get cleaned into plain text after copy and paste

### ISSUE THREAD

**Issue by eban5** [BluestoneLogic/medium-editor#76]
### We don't want the user to have to re-format content after copying and pasting sections. See editor options `cleanPastedHTML: false,` and `forcePlainText: false,` to check if they're being overridden.

**Comment by jwz2kn** [comment]
Played around with this a bit, the parent branch from yabwe actually has the same issue. It may be intentional that it loses formatting--- To keep formatting, we'd have to change the innerHTML of a section and not just pasting text.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#76
