### ISSUE TITLE
Remove capability of embedded extra media

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#82]
Currently, the user can embed extra media like Twitter, Facebook, Youtube, some websites, etc., but that's extraneous and distracting. It does not fit the workflow of the DraftFinal user, because that sort of media embedding is much more common in blog post and social media work than it is in serious, professional level content creation.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#82
