### ISSUE TITLE
TOC does not work when in sidebar

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#85]
When the leading `<article>` tag is in the sidebar and the trailing `</article>` tag is below the `<div>` tags for .editable, it fails to actually create a table of contents. 

I believe the script for the TOC cannot read through multiple `<div>`s. 

For now, the TOC is an imitation of what it would actually look like. It is hard-coded. Therefore, not functional.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#85
