### ISSUE TITLE
TOC generates in order of header number

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#86]
The TOC list will put all H1s at the beginning, then H2, and then H3. Thus, it does not mimic the actual layout of the document. 

For example, if a document has these tags: 
H1
H2
H1.1
H3 

The TOC will be printed as:

- H1
- H1.1 
- H2 (one indent)
- H3 (two indent)

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#86
