### ISSUE TITLE
Port over sidebar components to React

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#93]
![screen shot 2016-07-25 at 11 22 17 am](https://cloud.githubusercontent.com/assets/11744033/17106645/1bfb00fe-525a-11e6-8027-61feb3b5e3e1.png)

We want all these UI components to be ported over to React, and moved out into separate JS files.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#93
