### ISSUE TITLE
Port over entire sidebar appearance to React

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#95]
![screen shot 2016-07-25 at 11 22 17 am](https://cloud.githubusercontent.com/assets/11744033/17155424/01b6edb2-5353-11e6-8a04-e11ffb4a0cfe.png)

We want the entire sidebar, not just its individual components, to be built with the React framework.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#95
